version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ./mongo:/data/db
    networks:
      - app-network
    restart: unless-stopped
  app:
    build: .
    container_name: app
    ports:
      - 3000:3000
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
networks:
  app-network: